name: widgetbook_base_components_example
on:
  push:
    branches:
      - main
    paths:
      - bricks/widgetbook_base_components/**
      - examples/widgetbook_base_components/**
      - .github/workflows/widgetbook_base_components.yaml
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Activate Mason
        run: dart pub global activate mason_cli
      - name: Build Brick in example
        working-directory: examples/widgetbook_base_components
        run: mason get; mason make widgetbook_base_components
      - name: Generate Widgetbook
        working-directory: examples/widgetbook_base_components
        run: dart run build_runner run
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          customArgs: -t lib/widgetbook.dart
          workingDir: examples/widgetbook_base_components
          baseHref: /brick-examples/widgetbook_base_components